/**
 * Map country labels (from visits data) → ISO 3166-1 alpha-2 for flagcdn.
 * Parenthetical notes like "(2 visits)" are stripped before lookup.
 */
const NAME_TO_ISO = {
  afghanistan: 'af',
  albania: 'al',
  algeria: 'dz',
  andorra: 'ad',
  angola: 'ao',
  'antigua and barbuda': 'ag',
  argentina: 'ar',
  armenia: 'am',
  australia: 'au',
  austria: 'at',
  azerbaijan: 'az',
  bahamas: 'bs',
  bahrain: 'bh',
  bangladesh: 'bd',
  barbados: 'bb',
  belarus: 'by',
  belgium: 'be',
  belize: 'bz',
  benin: 'bj',
  bhutan: 'bt',
  bolivia: 'bo',
  'bosnia and herzegovina': 'ba',
  botswana: 'bw',
  brazil: 'br',
  brunei: 'bn',
  bulgaria: 'bg',
  'burkina faso': 'bf',
  burundi: 'bi',
  'cabo verde': 'cv',
  cambodia: 'kh',
  cameroon: 'cm',
  canada: 'ca',
  'central african republic': 'cf',
  chad: 'td',
  chile: 'cl',
  china: 'cn',
  colombia: 'co',
  comoros: 'km',
  'republic of the congo': 'cg',
  'democratic republic of the congo': 'cd',
  'costa rica': 'cr',
  "côte d'ivoire": 'ci',
  "cote d'ivoire": 'ci',
  croatia: 'hr',
  cuba: 'cu',
  cyprus: 'cy',
  'czech republic': 'cz',
  czechia: 'cz',
  denmark: 'dk',
  djibouti: 'dj',
  dominica: 'dm',
  'dominican republic': 'do',
  ecuador: 'ec',
  egypt: 'eg',
  'el salvador': 'sv',
  'equatorial guinea': 'gq',
  eritrea: 'er',
  estonia: 'ee',
  eswatini: 'sz',
  ethiopia: 'et',
  fiji: 'fj',
  finland: 'fi',
  france: 'fr',
  gabon: 'ga',
  gambia: 'gm',
  germany: 'de',
  ghana: 'gh',
  greece: 'gr',
  grenada: 'gd',
  guatemala: 'gt',
  guinea: 'gn',
  'guinea-bissau': 'gw',
  guyana: 'gy',
  haiti: 'ht',
  honduras: 'hn',
  hungary: 'hu',
  iceland: 'is',
  indonesia: 'id',
  iran: 'ir',
  ireland: 'ie',
  israel: 'il',
  italy: 'it',
  jamaica: 'jm',
  japan: 'jp',
  jordan: 'jo',
  kazakhstan: 'kz',
  kenya: 'ke',
  kiribati: 'ki',
  kuwait: 'kw',
  kyrgyzstan: 'kg',
  laos: 'la',
  latvia: 'lv',
  lebanon: 'lb',
  lesotho: 'ls',
  liberia: 'lr',
  libya: 'ly',
  liechtenstein: 'li',
  lithuania: 'lt',
  luxembourg: 'lu',
  madagascar: 'mg',
  malawi: 'mw',
  malaysia: 'my',
  maldives: 'mv',
  mali: 'ml',
  malta: 'mt',
  'marshall islands': 'mh',
  mauritius: 'mu',
  mexico: 'mx',
  micronesia: 'fm',
  moldova: 'md',
  monaco: 'mc',
  mongolia: 'mn',
  montenegro: 'me',
  morocco: 'ma',
  mozambique: 'mz',
  myanmar: 'mm',
  namibia: 'na',
  nauru: 'nr',
  nepal: 'np',
  netherlands: 'nl',
  'new zealand': 'nz',
  nicaragua: 'ni',
  nigeria: 'ng',
  'north korea': 'kp',
  'north macedonia': 'mk',
  norway: 'no',
  oman: 'om',
  pakistan: 'pk',
  palau: 'pw',
  palestine: 'ps',
  panama: 'pa',
  'papua new guinea': 'pg',
  paraguay: 'py',
  peru: 'pe',
  philippines: 'ph',
  poland: 'pl',
  portugal: 'pt',
  qatar: 'qa',
  romania: 'ro',
  russia: 'ru',
  rwanda: 'rw',
  'saint kitts and nevis': 'kn',
  'saint lucia': 'lc',
  'saint vincent and the grenadines': 'vc',
  samoa: 'ws',
  'san marino': 'sm',
  'são tomé and príncipe': 'st',
  'sao tome and principe': 'st',
  'saudi arabia': 'sa',
  senegal: 'sn',
  serbia: 'rs',
  seychelles: 'sc',
  'sierra leone': 'sl',
  singapore: 'sg',
  slovakia: 'sk',
  slovenia: 'si',
  'solomon islands': 'sb',
  somalia: 'so',
  'south africa': 'za',
  'south korea': 'kr',
  'south sudan': 'ss',
  spain: 'es',
  'sri lanka': 'lk',
  sudan: 'sd',
  suriname: 'sr',
  sweden: 'se',
  switzerland: 'ch',
  syria: 'sy',
  tajikistan: 'tj',
  tanzania: 'tz',
  thailand: 'th',
  'timor-leste': 'tl',
  togo: 'tg',
  tonga: 'to',
  'trinidad & tobago': 'tt',
  'trinidad and tobago': 'tt',
  tunisia: 'tn',
  turkey: 'tr',
  turkmenistan: 'tm',
  tuvalu: 'tv',
  uganda: 'ug',
  ukraine: 'ua',
  'united arab emirates': 'ae',
  'united kingdom': 'gb',
  'united states': 'us',
  uruguay: 'uy',
  uzbekistan: 'uz',
  vanuatu: 'vu',
  'vatican city': 'va',
  venezuela: 've',
  vietnam: 'vn',
  yemen: 'ye',
  zambia: 'zm',
  zimbabwe: 'zw',
}

/** Strip " (2 visits)" / " (2)" etc. and lowercase */
export function normalizeCountryName(label) {
  return String(label)
    .replace(/\s*\([^)]*\)\s*/g, '')
    .trim()
    .toLowerCase()
}

export function getCountryIso(label) {
  return NAME_TO_ISO[normalizeCountryName(label)] || null
}

/** Small PNG flag from flagcdn (no API key). */
export function getFlagUrl(label, width = 40) {
  const iso = getCountryIso(label)
  if (!iso) return null
  return `https://flagcdn.com/w${width}/${iso}.png`
}

export function getFlagSrcSet(label) {
  const iso = getCountryIso(label)
  if (!iso) return null
  return `https://flagcdn.com/w40/${iso}.png 1x, https://flagcdn.com/w80/${iso}.png 2x`
}
