/** PM foreign visits by year */
export const VISITS = [
  {
    year: 2014,
    note: null,
    countries: [
      'Bhutan',
      'Brazil',
      'Nepal (2 visits)',
      'Japan',
      'United States',
      'Myanmar',
      'Australia',
      'Fiji',
    ],
  },
  {
    year: 2015,
    note: null,
    countries: [
      'Seychelles',
      'Mauritius',
      'Sri Lanka',
      'Singapore (2)',
      'France (2)',
      'Germany',
      'Canada',
      'China',
      'Mongolia',
      'South Korea',
      'Bangladesh',
      'Uzbekistan',
      'Kazakhstan',
      'Russia',
      'Turkmenistan',
      'Kyrgyzstan',
      'Tajikistan',
      'United Arab Emirates',
      'Ireland',
      'United States',
      'United Kingdom',
      'Turkey',
      'Malaysia',
      'Afghanistan',
      'Pakistan',
    ],
  },
  {
    year: 2016,
    note: null,
    countries: [
      'Belgium',
      'United States (2)',
      'Saudi Arabia',
      'Iran',
      'Afghanistan',
      'Qatar',
      'Switzerland',
      'Mexico',
      'Mozambique',
      'South Africa',
      'Tanzania',
      'Kenya',
      'Vietnam',
      'Laos',
      'China',
      'Japan',
    ],
  },
  {
    year: 2017,
    note: null,
    countries: [
      'Portugal',
      'United States',
      'Netherlands',
      'Germany',
      'Spain',
      'Russia',
      'Kazakhstan',
      'Myanmar',
      'China',
      'Philippines',
    ],
  },
  {
    year: 2018,
    note: null,
    countries: [
      'Palestine',
      'United Arab Emirates',
      'Oman',
      'Sweden',
      'United Kingdom',
      'Germany',
      'China',
      'Nepal',
      'Russia',
      'Singapore',
      'Indonesia',
      'Malaysia',
      'Argentina',
    ],
  },
  {
    year: 2019,
    note: null,
    countries: [
      'South Korea',
      'Kyrgyzstan',
      'Maldives',
      'Sri Lanka',
      'France',
      'United Arab Emirates',
      'Bahrain',
      'United States',
      'Russia',
      'Saudi Arabia',
      'Thailand',
      'Brazil',
    ],
  },
  {
    year: 2020,
    note: 'No foreign visits (COVID-19 pandemic)',
    countries: [],
  },
  {
    year: 2021,
    note: null,
    countries: ['Bangladesh', 'United States', 'Italy', 'United Kingdom'],
  },
  {
    year: 2022,
    note: null,
    countries: [
      'Germany (2)',
      'Denmark',
      'France',
      'Nepal',
      'Japan (2)',
      'United Arab Emirates',
      'Uzbekistan',
      'Indonesia',
    ],
  },
  {
    year: 2023,
    note: null,
    countries: [
      'Japan',
      'Papua New Guinea',
      'Australia',
      'United States',
      'Egypt',
      'France',
      'United Arab Emirates',
      'Greece',
      'South Africa',
    ],
  },
  {
    year: 2024,
    note: null,
    countries: [
      'United Arab Emirates',
      'Qatar',
      'Italy',
      'Austria',
      'Russia',
      'Poland',
      'Brunei',
      'Singapore',
      'Nigeria',
      'Brazil',
      'Guyana',
      'Kuwait',
    ],
  },
  {
    year: 2025,
    note: null,
    countries: [
      'France',
      'United States',
      'Canada',
      'Cyprus',
      'Croatia',
      'Ghana',
      'Trinidad & Tobago',
      'Argentina',
      'Brazil',
      'Namibia',
      'United Kingdom',
      'Maldives',
      'Japan',
      'China',
      'Bhutan',
      'South Africa',
      'Jordan',
      'Ethiopia',
      'Oman',
    ],
  },
  {
    year: 2026,
    note: 'As of 12 July 2026',
    countries: [
      'Malaysia',
      'Israel',
      'United Arab Emirates',
      'Netherlands',
      'Sweden',
      'Norway',
      'Italy',
      'France',
      'Slovakia',
      'Seychelles',
      'Indonesia',
      'Australia',
      'New Zealand',
    ],
  },
]

/** Countries not visited (as of list), grouped by region */
export const UNVISITED_REGIONS = [
  {
    region: 'Europe',
    countries: [
      'Albania',
      'Andorra',
      'Belarus',
      'Bosnia and Herzegovina',
      'Bulgaria',
      'Czech Republic',
      'Estonia',
      'Finland',
      'Hungary',
      'Iceland',
      'Latvia',
      'Liechtenstein',
      'Lithuania',
      'Luxembourg',
      'Malta',
      'Moldova',
      'Monaco',
      'Montenegro',
      'North Macedonia',
      'Romania',
      'San Marino',
      'Serbia',
      'Slovenia',
      'Ukraine',
      'Vatican City',
    ],
  },
  {
    region: 'Africa',
    countries: [
      'Algeria',
      'Angola',
      'Benin',
      'Botswana',
      'Burkina Faso',
      'Burundi',
      'Cabo Verde',
      'Cameroon',
      'Central African Republic',
      'Chad',
      'Comoros',
      'Republic of the Congo',
      'Democratic Republic of the Congo',
      "Côte d'Ivoire",
      'Djibouti',
      'Equatorial Guinea',
      'Eritrea',
      'Eswatini',
      'Gabon',
      'Gambia',
      'Guinea',
      'Guinea-Bissau',
      'Lesotho',
      'Liberia',
      'Libya',
      'Madagascar',
      'Malawi',
      'Mali',
      'Morocco',
      'Rwanda',
      'São Tomé and Príncipe',
      'Senegal',
      'Sierra Leone',
      'Somalia',
      'South Sudan',
      'Sudan',
      'Togo',
      'Tunisia',
      'Uganda',
      'Zambia',
      'Zimbabwe',
    ],
  },
  {
    region: 'Asia',
    countries: [
      'Armenia',
      'Azerbaijan',
      'Cambodia',
      'Lebanon',
      'North Korea',
      'Syria',
      'Timor-Leste',
      'Yemen',
    ],
  },
  {
    region: 'Oceania',
    countries: [
      'Kiribati',
      'Marshall Islands',
      'Micronesia',
      'Nauru',
      'Palau',
      'Samoa',
      'Solomon Islands',
      'Tonga',
      'Tuvalu',
      'Vanuatu',
    ],
  },
  {
    region: 'North America & Caribbean',
    countries: [
      'Antigua and Barbuda',
      'Bahamas',
      'Barbados',
      'Belize',
      'Costa Rica',
      'Cuba',
      'Dominica',
      'Dominican Republic',
      'El Salvador',
      'Grenada',
      'Guatemala',
      'Haiti',
      'Honduras',
      'Jamaica',
      'Nicaragua',
      'Panama',
      'Saint Kitts and Nevis',
      'Saint Lucia',
      'Saint Vincent and the Grenadines',
    ],
  },
  {
    region: 'South America',
    countries: [
      'Bolivia',
      'Chile',
      'Colombia',
      'Ecuador',
      'Paraguay',
      'Peru',
      'Suriname',
      'Uruguay',
      'Venezuela',
    ],
  },
]

export const NOTABLE_UNVISITED = [
  'Finland',
  'Czech Republic',
  'Hungary',
  'Romania',
  'Chile',
  'Colombia',
  'Luxembourg',
  'Iceland',
]

export const NOTABLE_NOTE =
  'Notable G20/OECD countries still unvisited, plus newer EU members in Eastern Europe'
